### ISSUE TITLE
Attach APK to release?

### ISSUE THREAD

**Issue by IzzySoft** [rogerta/secrets-for-android#138]
The readme says "Only use the download link on this site if your device does not have access to the market." Unfortunately, that link is missing. May I suggest you add the `.apk` file to the `releases/` page (see [Creating Releases](https://help.github.com/articles/creating-releases/) in the Github User Documentation for details – it's quite easy to accomplish)? I'd then offer to automatically grab it and put it into [my repo](https://android.izzysoft.de/repo) whenever you publish a new version. So those without access to Playstore could still get their updates automatically.

Thanks in advance!

**Comment by rogerta** [comment]
Hi Izzy,

hmm, that probably got dropped when the project was auto moved from
code.google.com to github.  Thanks for heads up.  The download link is
https://drive.google.com/folderview?id=0B0s1mmDneTE2bG5rUVlXempGc2c&usp=sharing

I'll also look into github releasing.

=================================================
Roger Tawa
http://tawacentral.net/
[When you stop, you're done.]

**Comment by IzzySoft** [comment]
@rogerta Thanks for the fast response! Looking forward to the Github attachment then (as that's where my repo script can check – it cannot deal with drive). If the `.apk` is available here, please just state so in this issue (which I monitor) – I'll then integrate it with my repo ASAP.

**Comment by IzzySoft** [comment]
Any progress? Are you still working on the app?

**Comment by IzzySoft** [comment]
Hm, seems dead then – so I'm closing this. Feel free to reopen if you revive the project, my offer remains standing.
