### ISSUE TITLE
Remote deletion of secrets

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rogerta/secrets-for-android#5]
```
Allow the secrets to be deleted from the phone remotely, so that if the
phone is lost or stolen the secrets can be removed from the device.
```

Original issue reported on code.google.com by `roge...@gmail.com` on 10 Apr 2009 at 1:31

**Comment by bcwhite0** [comment]
Secrets needs to be able to work in a fully offline situation and there's no way of knowing when that will be happen.  Depending on anything "cloud" isn't going to work.

Android phones now have remote-wipe ability which satisfies the general request.  However, this isn't enough.  A knowledgeable attacker just needs to extract the data in the time before the phone is wiped.

The proper security is a strong password and an expensive calculation of the final key from that password.  That way, even with the actual data available for offline cracking, it costs more to break the password than the value of the data protected by it.
